apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-sample
    app.kubernetes.io/part-of: application-test-2
  name: java-quarkus-sample
  namespace: sbudhwar-1
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: java-quarkus-sample
    weight: 100
status: {}
